export type FrontMatterType = {
  title: string;
  short_description: string;
  date: Date;
  user?: string;
  category?: string[];
};

export type PostWithFrontmatterType = {
  body: string;
  path?: string;
} & FrontMatterType;

// Generated by https://quicktype.io

export type PostSearchList = {
  total_count: number;
  incomplete_results: boolean;
  items: Item[];
};

export type PostSearchResult = {
  data: Item[];
  totalCount: number;
  nextPage: number;
};

export type Item = {
  path: string;
};
